## application.yaml
##Remove the '#' on keys for tests and put your own IAM AWS keys
cloud:
   aws:
      credentials:
         access-key: #AKIAYFMYRDNP46O4Z2SG
         secret-key: #MMqkWBvlkNQkY9RR57ux9wGyXtpZXlcmi5yVCJzI	
      region:
         static: us-east-1
      stack:
         auto: false
      
      
application:
   bucket:
      name: jayaws

spring:
   servlet:
      multipart:
         enabled: true
         file-size-threshold: 2MB
         max-file-size: 10MB
         max-request-size: 20MB		

server:
   port: 2001